services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: tala1234
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/menu_api
    ports:
      - "3001:3001"
    depends_on:
      - db  
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6370"

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/menu_api
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0